name: ci

on:
  pull_request:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  build-shell:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - macos-latest
          - macos-latest-large
          - ubuntu-latest
          - ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v6

      - uses: ALT-F4-LLC/setup-vorpal-action@main
        with:
          registry-backend: s3
          registry-backend-s3-bucket: altf4llc-vorpal-registry
          version: nightly
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: vorpal build 'docket-shell'

      - uses: actions/upload-artifact@v6
        with:
          name: vorpal-lock-${{ runner.arch }}-${{ runner.os }}
          path: Vorpal.lock

  build:
    needs:
      - build-shell
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        artifact:
          - docket
        runner:
          - macos-latest
          - macos-latest-large
          - ubuntu-latest
          - ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v6

      - uses: ALT-F4-LLC/setup-vorpal-action@main
        with:
          registry-backend: s3
          registry-backend-s3-bucket: altf4llc-vorpal-registry
          version: nightly
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: |
          ARTIFACT_PATH=$(vorpal build --path '${{ matrix.artifact }}')/bin/docket
          echo "ARTIFACT_PATH=$ARTIFACT_PATH" >> $GITHUB_ENV

      - run: |
          echo "ARCH=$(uname -m | tr '[:upper:]' '[:lower:]' | sed 's/arm64/aarch64/')" >> $GITHUB_ENV
          echo "OS=$(uname -s | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - run: |
          ARCHIVE_NAME="docket-${{ env.ARCH }}-${{ env.OS }}.tar.gz"
          tar -czf "$ARCHIVE_NAME" -C "$(dirname ${{ env.ARTIFACT_PATH }})" "$(basename ${{ env.ARTIFACT_PATH }})"
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v6
        with:
          name: docket-dist-${{ env.ARCH }}-${{ env.OS }}
          path: ${{ env.ARCHIVE_NAME }}

  release:
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
    needs:
      - build
    permissions:
      attestations: write
      contents: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v7
        with:
          fail-on-cache-miss: true
          merge-multiple: true
          pattern: docket-dist-*
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: dist/*
          name: ${{ github.ref_name }}
          prerelease: true
          tag_name: ${{ github.ref }}

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: dist/*
