name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-shell:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - macos-latest
          - macos-latest-large
          - ubuntu-latest
          - ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v6

      - uses: ALT-F4-LLC/setup-vorpal-action@main
        with:
          registry-backend: s3
          registry-backend-s3-bucket: altf4llc-vorpal-registry
          version: nightly
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: vorpal build 'docket-shell'

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ runner.arch }}-${{ runner.os }}-vorpal-lock
          path: Vorpal.lock

  build:
    needs:
      - build-shell
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        artifact:
          - docket
        runner:
          - macos-latest
          - macos-latest-large
          - ubuntu-latest
          - ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v6

      - uses: ALT-F4-LLC/setup-vorpal-action@main
        with:
          registry-backend: s3
          registry-backend-s3-bucket: altf4llc-vorpal-registry
          version: nightly
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: vorpal build '${{ matrix.artifact }}'
